### ISSUE TITLE
Issue with show-all

### ISSUE THREAD

**Issue by WuhanMonkey** [WuhanMonkey/UDPServerClient#4]
Tested with continue. Out of Index on line 144 which just printing out the message. show-all still been broadcast out. Working on it now.

**Comment by WuhanMonkey** [comment]
Update on show-all. Problem solved. Caused by the newline when read form the file. However, I noticed that for 2 nodes the order of some command is still not right.

**Comment by WuhanMonkey** [comment]
The problem about the out of order of the commands seems solved. The problem is that we didn't handle input command of 'update' appropriately. Another problem raised about 'show-all'. We still needs to broadcast it because if it handled locally when it is been read, the broadcast of previous command might not been processed yet. I will changed it on send thread and listen thread in order to handle it properly.

**Comment by WuhanMonkey** [comment]
Handled the problem of show-all. It now works fine.

**Comment by Staed** [comment]
Fixed the output of show-all and made it thread-safe. Previously in it's thread-unsafe 
form, it would cause a rare error due to data-races.

This is possibly due to smaller polling intervals (0.25 instead of 0.5) for which the thread
advances to the next command despite the for-loop in show-all not finishing yet.

Closing.
